/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.grupo5.vista;

import arbolBinario.ArbolAVL;
import arbolBinario.NodoArbol;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import com.grupo5.arbolavlsimulator.AlgoritmosArbol;

/**
 *
 * @author mmall
 */
public class Canvas extends javax.swing.JPanel {

    /**
     * Creates new form Canvas
     * @param arbol
     */
    public Canvas(ArbolAVL<Integer> arbol) {
        initComponents();
        Canvas.arbol = arbol;
    }
    
    public static ArbolAVL<Integer> arbol;
    
    /**
     *
     * @param Arbol
     */
    public void setArbol(ArbolAVL Arbol){
        arbol = Arbol;
    }
    
    public void repintar(){
        repaint();
    }
    
    @Override
    public void paint(Graphics g){
        super.paint(g);
        dibujarNodo(g, getWidth()/2, 20, arbol.getRaiz());
        //dibujarNodo();
    }
    
    public void dibujarNodo(Graphics g, int x, int y, NodoArbol<Integer> nodo){
        if(nodo != null) {
            int anchoExtra = AlgoritmosArbol.numeroDeNodos(nodo)*(50/2);
                  
            //int anchoExtra = 0;
                    //this.arbol.nodosCompletos(nodo)*(this.ancho/2);
            g.setColor(Color.GREEN);
            //g.setColor(Color.GREEN);
            g.fillOval(x, y, 30, 30);
            g.setColor(Color.BLACK);
            g.setFont(new Font( "Arial", Font.BOLD, 14 ) );
            g.drawString(nodo.getClave().toString(), x+8, y+18);
            g.setColor(Color.BLACK);
            if(nodo.getIz() != null)
		g.drawLine(x+15, y+15, x-50-anchoExtra+15, y+50+15);
            if(nodo.getDe() != null)
		g.drawLine(x+15, y+15, x+50+anchoExtra+15, y+50+15);
            dibujarNodo(g, x-50-anchoExtra, y+50, nodo.getIz());
            dibujarNodo(g, x+50+anchoExtra, y+50, nodo.getDe());
	}
    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 422, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 333, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
